[server]
enableStaticServing = true

[theme]
base = 'dark'
font = "DM Sans:https://fonts.googleapis.com/css2?family=DM Sans:ital,wght@0,400..700;1,400..700&display=swap"
backgroundColor = "#101222"
dataframeBorderColor = "#32344a"
dataframeHeaderBackgroundColor = "#101222"
textColor = '#ffffff'
