[server]
enableStaticServing = true

[theme]
base = 'dark'
font = "DM Sans:https://fonts.googleapis.com/css2?family=DM Sans:ital,wght@0,400..700;1,400..700&display=swap"
primaryColor = "#d6a513" #72CBFD
blueColor = '#339cff'
yellowColor = '#F1C647'
backgroundColor = "#101222"
dataframeBorderColor = "#32344a"
dataframeHeaderBackgroundColor = "#101222"
textColor = '#ffffff'

[theme.sidebar]
primaryColor = "#0076B8"
backgroundColor = "#32344A"
secondaryBackgroundColor = "292C42"
